# https://hub.docker.com/_/mysql/
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql/ 
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: cheap
      MYSQL_USER: Camel
      MYSQL_PASSWORD: 8Fish8

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
